#!/bin/zsh

# Prepare
export ZPLUG_HOME="/tmp/zplug-$RANDOM"
export ZPLUG_REPOS="$ZPLUG_HOME/repos"
mkdir -p "$ZPLUG_HOME" "$ZPLUG_REPOS"

# Prepare
source "$ZPLUG_ROOT/init.zsh"
zplugs=()
zplug clear

# as
{
    # plugin
    zplug "tcnksm/docker-alias", \
        use:zshrc
    # command
    zplug "Jxck/dotfiles", \
        as:command, \
        use:"bin/{histuniq,color}"
}

# at
{
    # branch
    zplug "b4b4r07/enhancd", \
        at:v1, \
        use:"*.sh"
    # commit
    zplug "mollifier/anyframe", \
        at:4c23cb60
}

# from
{
    # github
    zplug "zsh-users/zsh-syntax-highlighting", \
        from:github, \
        as:plugin
    zplug "mrowa44/emojify", \
        from:github, \
        as:command
    # bitbucket
    zplug "b4b4r07/hello_bitbucket", \
        from:bitbucket, \
        as:command, \
        hook-build:"chmod 755 *.sh", \
        use:"*.sh"
    # oh-my-zsh
    zplug "plugins/git", \
        from:oh-my-zsh
    zplug "plugins/cp", \
        from:oh-my-zsh
    zplug "plugins/emoji", \
        from:oh-my-zsh
    # gh-r
    zplug "peco/peco", \
        as:command, \
        from:gh-r, \
        frozen:1
    zplug "junegunn/fzf-bin", \
        as:command, \
        from:gh-r, \
        rename-to:fzf, \
        use:"*darwin*amd64*"
    # gist
    zplug "b4b4r07/79ee61f7c140c63d2786", \
        from:gist, \
        as:command, \
        use:get_last_pane_path.sh
    # local
    ## skip
}

# depth
# dir
# frozen
# hook-build
# hook-load
# if
# ignore
# lazy
# nice
# on

# rename-to
{
    zplug "stedolan/jq", \
        from:gh-r, \
        as:command, \
        rename-to:jq
}

# use

zplug install        || exit 1
zplug load --verbose || exit 1
