#!/bin/zsh

source "$ZPLUG_ROOT/init.zsh"

zplugs=()
zplug clear

zplug "plugins/git", \
    from:oh-my-zsh
zplug "b4b4r07/enhancd", \
    at:v1, \
    use:"*.sh"
zplug "b4b4r07/79ee61f7c140c63d2786", \
    from:gist, \
    as:command, \
    use:get_last_pane_path.sh
zplug "b4b4r07/hello_bitbucket", \
    from:bitbucket, \
    as:command, \
    hook-build:"chmod 755 *.sh", \
    use:"*.sh"
zplug "mrowa44/emojify", \
    as:command
zplug "peco/peco", \
    as:command, \
    from:gh-r, \
    frozen:1
zplug "stedolan/jq", \
    from:gh-r, \
    as:command, \
    rename-to:jq
zplug "b4b4r07/emoji-cli", \
    on:"stedolan/jq"
zplug "Jxck/dotfiles", \
    as:command, \
    use:"bin/{histuniq,color}"

zplug install
zplug load --verbose
