#!/bin/zsh

set -e

source "$ZPLUG_ROOT/init.zsh"

zplugs=()
zplug clear

zplug "plugins/git", \
    from:oh-my-zsh
zplug "b4b4r07/enhancd", \
    use:init.sh
zplug "mrowa44/emojify", \
    as:command
zplug "peco/peco", \
    as:command, \
    from:gh-r, \
    frozen:1

zplug install
zplug load --verbose
