#!/bin/zsh

local    arg="$1" package
local -a parsed_zplugs
local    at
local    default="master"

if [[ -n $arg ]] && ! __zplug::base::base::zpluged "$arg"; then
    __zplug::io::print::f \
        --die \
        --zplug \
        "$arg: no package managed by zplug\n"
    return 1
fi

package="${arg}, ${zplugs[$arg]%, }"
parsed_zplugs=(${(s/, /)package/,  */, })

at="${parsed_zplugs[(k)at:*]#at:*}"
if [[ -z $at ]]; then
    zstyle -s ":zplug:tag" at at
fi

if [[ "$(__from__ "$arg")" == "gh-r" ]]; then
    default="latest"
    if [[ -n $at ]]; then
        at="tag/$at"
    fi
fi

echo "${at:-$default}"
